// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {timer} from '../models';

export function GetState():Promise<timer.State>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function Pause():Promise<timer.State>;

export function Quit():Promise<void>;

export function Reset():Promise<timer.State>;

export function SetAlwaysOnTop(arg1:boolean):Promise<timer.State>;

export function SetCloseToTray(arg1:boolean):Promise<timer.State>;

export function SetCurrentDuration(arg1:number):Promise<timer.State>;

export function SetLanguage(arg1:string):Promise<timer.State>;

export function SetSingleKeyShortcuts(arg1:boolean):Promise<timer.State>;

export function SetSoundEnabled(arg1:boolean):Promise<timer.State>;

export function SetTheme(arg1:string):Promise<timer.State>;

export function ShowWindow():Promise<void>;

export function Skip():Promise<timer.State>;

export function Start():Promise<timer.State>;

export function Toggle():Promise<timer.State>;

export function ToggleWindow():Promise<void>;

export function UpdateSettings(arg1:timer.Settings):Promise<timer.State>;
