// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.State>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function Pause():Promise<main.State>;

export function Quit():Promise<void>;

export function Reset():Promise<main.State>;

export function SetAlwaysOnTop(arg1:boolean):Promise<main.State>;

export function SetCurrentDuration(arg1:number):Promise<main.State>;

export function SetLanguage(arg1:string):Promise<main.State>;

export function SetSingleKeyShortcuts(arg1:boolean):Promise<main.State>;

export function SetSoundEnabled(arg1:boolean):Promise<main.State>;

export function ShowWindow():Promise<void>;

export function Skip():Promise<main.State>;

export function Start():Promise<main.State>;

export function Toggle():Promise<main.State>;

export function ToggleWindow():Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<main.State>;
