// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetCurrentDuration(arg1) {
  return window['go']['main']['App']['SetCurrentDuration'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetNotificationsEnabled(arg1) {
  return window['go']['main']['App']['SetNotificationsEnabled'](arg1);
}

export function SetSingleKeyShortcuts(arg1) {
  return window['go']['main']['App']['SetSingleKeyShortcuts'](arg1);
}

export function SetSoundEnabled(arg1) {
  return window['go']['main']['App']['SetSoundEnabled'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Skip() {
  return window['go']['main']['App']['Skip']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
